### ISSUE TITLE
Missing makefiles for examples

### ISSUE THREAD

**Issue by reaperhulk** [kudelskisecurity/cdf#2]
`make examples-all` does `cd examples; make` but there's no makefile present in the examples dir. As a workaround, a bash way to compile all the examples would be `for file in *.go; do go build $file;done`

**Comment by veorq** [comment]
Here it is https://github.com/kudelskisecurity/cdf/blob/master/examples/makefile

**Comment by reaperhulk** [comment]
Thanks for the super quick responses!
